[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "opvault"
version = "0.0.1"
dependencies = [
    'importlib-metadata; python_version<"3.11"',
    'verystable',
    'bip32',
    'clii',
]
